version: '3.3'
services:
  auth:
    container_name: signal-service
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - redis_net
      - postgres_net
      - ingress_net
    env_file:
      - ../.env
    environment:
      - VIRTUAL_HOST=signal.localhost, signal.staging.mydomain.com
      - LETSENCRYPT_HOST=signal.localhost, signal.staging.mydomain.com
    healthcheck:
      test: curl --fail http://127.0.0.1/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  db:
    container_name: postgres
    image: postgres:11.9-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgre
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql
    networks:
      - default
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=valizadearshia8@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - VIRTUAL_HOST= pga.localhost
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - default
      - ingress_net

  proxy:
    container_name: ingress
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./default_location:/etc/nginx/vhost.d/default_location
  whoami:
    container_name: whoami
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.localhost,whoami.staging.mydomain.com

networks:
  ingress_net:
  postgres_net: